"""One Python version everywhere: `.python-version` names it, and the image, CI, the
dependency locks, ruff and the sidecar forwarder use the same one; start.sh makes the native
virtualenv with it, remakes one made with another, and refuses to start without it.
"""

import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
VERSION = (REPO / ".python-version").read_text().strip()


def test_the_version_is_one_minor_version():
    assert re.fullmatch(r"3\.\d+", VERSION)


def test_the_image_ci_locks_ruff_and_forwarder_use_it():
    assert f"FROM python:{VERSION}-slim" in (REPO / "Dockerfile").read_text()
    ci = (REPO / ".github" / "workflows" / "ci.yml").read_text()
    assert re.findall(r'python-version: "([\d.]+)"', ci) == [VERSION]
    script = (REPO / "scripts" / "update_requirements.sh").read_text()
    assert set(re.findall(r"python:([\d.]+)-slim", script)) == {VERSION}
    for lock in ("requirements.txt", "requirements-dev.txt"):
        header = (REPO / lock).read_text().splitlines()[0]
        assert header.endswith(f"with Python {VERSION}."), lock
    pyproject = (REPO / "pyproject.toml").read_text()
    assert f'target-version = "py{VERSION.replace(".", "")}"' in pyproject
    assert f"MCP_SIDECAR_FORWARDER_IMAGE=python:{VERSION}-slim" in (
        REPO / ".env.example"
    ).read_text()
    assert f'or "python:{VERSION}-slim"' in (REPO / "app" / "host" / "helper.py").read_text()


def test_each_lock_has_one_header():
    for lock in ("requirements.txt", "requirements-dev.txt"):
        text = (REPO / lock).read_text()
        assert text.count("# Generated by scripts/update_requirements.sh") == 1, lock


# --- start.sh and the virtualenv, with fake interpreters ---

FAKE_PYTHON = """#!/bin/bash
# A stand-in interpreter that reports VERSION and makes a virtualenv of itself.
if [ "$1" = "-c" ]; then echo "{version}"; exit 0; fi
if [ "$1" = "--version" ]; then echo "Python {version}.0"; exit 0; fi
if [ "$1" = "-m" ] && [ "$2" = "venv" ]; then
  mkdir -p "$3/bin" && cp "$0" "$3/bin/python" && echo "{version}" > "$3/made-with"; exit 0
fi
exit 3
"""


def _functions() -> str:
    script = (REPO / "start.sh").read_text()
    start = script.index("# The project's Python")
    return script[start : script.index("setup_venv() {")]


def _tools(tmp_path: Path) -> Path:
    """Every tool of /usr/bin and /bin but the Python interpreters: only the fakes count."""
    folder = tmp_path / "tools"
    folder.mkdir()
    for directory in (Path("/usr/bin"), Path("/bin")):
        for tool in directory.iterdir():
            link = folder / tool.name
            if not tool.name.startswith("python") and not link.exists():
                link.symlink_to(tool)
    return folder


def _run(tmp_path: Path, interpreters: dict[str, str]):
    project = tmp_path / "project"
    project.mkdir(exist_ok=True)
    (project / ".python-version").write_text(VERSION + "\n")
    fakes = tmp_path / "fakes"
    fakes.mkdir(exist_ok=True)
    for name, version in interpreters.items():
        (fakes / name).write_text(FAKE_PYTHON.replace("{version}", version))
        (fakes / name).chmod(0o755)
    tools = tmp_path / "tools" if (tmp_path / "tools").exists() else _tools(tmp_path)
    code = f'REPO_DIR="{project}"\n{_functions()}\nensure_venv_python\n'
    return subprocess.run(
        ["/bin/bash", "-c", code],
        cwd=project,
        capture_output=True,
        text=True,
        env={"PATH": f"{fakes}:{tools}", "HOME": str(tmp_path)},
        timeout=30,
    ), project


def test_without_the_version_it_refuses_and_makes_nothing(tmp_path):
    run, project = _run(tmp_path, {"python3": "3.12"})
    assert run.returncode == 1
    assert f"Python {VERSION} is required" in run.stderr and "Python 3.12" in run.stderr
    assert not (project / ".venv").exists()


def test_it_prefers_the_versioned_interpreter_over_another_python3(tmp_path):
    run, project = _run(tmp_path, {"python3": "3.12", f"python{VERSION}": VERSION})
    assert run.returncode == 0, run.stderr
    assert (project / ".venv" / "made-with").read_text().strip() == VERSION


def test_a_python3_of_the_version_is_enough(tmp_path):
    run, project = _run(tmp_path, {"python3": VERSION})
    assert run.returncode == 0, run.stderr
    assert (project / ".venv" / "made-with").read_text().strip() == VERSION


def test_a_virtualenv_of_another_version_is_made_again(tmp_path):
    run, project = _run(tmp_path, {"python3": "3.12"})
    (project / ".venv" / "bin").mkdir(parents=True)
    old = project / ".venv" / "bin" / "python"
    old.write_text(FAKE_PYTHON.replace("{version}", "3.12"))
    old.chmod(0o755)
    run, project = _run(tmp_path, {f"python{VERSION}": VERSION})
    assert run.returncode == 0, run.stderr
    assert "uses Python 3.12" in run.stdout and "recreating it" in run.stdout
    assert (project / ".venv" / "made-with").read_text().strip() == VERSION


def test_a_virtualenv_of_the_version_is_kept(tmp_path):
    run, project = _run(tmp_path, {"python3": VERSION})
    (project / ".venv" / "keep").write_text("x")
    run, project = _run(tmp_path, {"python3": VERSION})
    assert run.returncode == 0 and (project / ".venv" / "keep").exists()
    assert "recreating" not in run.stdout
