"""initial schema

Revision ID: 05d7f3e9c350
Revises: 
Create Date: 2026-09-18 11:05:28.642405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '05d7f3e9c350'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'email', 'matrix', name='channel', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('raw_address', app.db.types.EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='uq_channel_external_id')
    )
    op.create_index(op.f('ix_channel_identities_external_id'), 'channel_identities', ['external_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_identity_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('chat', 'admin', name='permissionkind', native_enum=False), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_identity_id'], ['channel_identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_identity_id', 'kind', name='uq_channel_identity_kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    op.drop_index(op.f('ix_channel_identities_external_id'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_table('users')
    # ### end Alembic commands ###
