"""add retention config

One row of retention periods (days, null = kept for ever) and the counts of the last run.

Revision ID: 17b62939a387
Revises: d3d0e7313cdc
Create Date: 2026-09-27 21:07:44.572050

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17b62939a387"
down_revision: str | Sequence[str] | None = "d3d0e7313cdc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retention_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("messages_days", sa.Integer(), nullable=True),
        sa.Column("tool_calls_days", sa.Integer(), nullable=True),
        sa.Column("conversations_days", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retention_config")
    # ### end Alembic commands ###
