"""add action_logs and access_requests

Revision ID: 620c8b04570e
Revises: 05d7f3e9c350
Create Date: 2026-09-18 13:49:10.585916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.types


# revision identifiers, used by Alembic.
revision: str = '620c8b04570e'
down_revision: Union[str, Sequence[str], None] = '05d7f3e9c350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'email', 'matrix', name='channel', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('first_message_text', app.db.types.EncryptedString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='requeststatus', native_enum=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='uq_request_channel_external_id')
    )
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('telegram', 'email', 'matrix', name='channel', native_enum=False), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='direction', native_enum=False), nullable=False),
    sa.Column('text', app.db.types.EncryptedString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_created_at'), 'action_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_logs_created_at'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
