#!/usr/bin/env bash
# Regenerate the dependency locks.
#
#   requirements.in      direct runtime dependencies, loose (edit this one)
#   requirements-dev.in  test and tooling dependencies, loose (edit this one)
#   requirements.txt     the lock the image, CI and start.sh install
#   requirements-dev.txt the lock CI installs (runtime lock + test tooling)
#
# The locks are resolved inside python:3.14-slim, the interpreter of the
# Docker image and of CI, so they do not depend on the Python installed on
# this machine.
#
#   scripts/update_requirements.sh            re-resolve with the newest versions
#   scripts/update_requirements.sh --keep     re-resolve keeping current pins
#                                             (after editing an .in file)
#   scripts/update_requirements.sh --only PKG [PKG ...]
#                                             keep every pin but move the named
#                                             packages to their newest version (a
#                                             security fix that pip-audit reports)
#
# Review the diff like code, then run the tests and `pip-audit`.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

UPGRADE="--upgrade"
if [ "${1:-}" = "--keep" ]; then
  UPGRADE=""
elif [ "${1:-}" = "--only" ]; then
  shift
  if [ "$#" -eq 0 ]; then
    echo "usage: scripts/update_requirements.sh --only PKG [PKG ...]" >&2
    exit 2
  fi
  UPGRADE=""
  for package in "$@"; do
    case "$package" in
      *[!A-Za-z0-9._-]*) echo "not a package name: $package" >&2; exit 2 ;;
    esac
    UPGRADE="$UPGRADE --upgrade-package $package"
  done
fi

docker run --rm -v "$PWD":/work -w /work python:3.14-slim sh -c "
  set -e
  pip install --quiet pip-tools
  pip-compile --quiet ${UPGRADE} --strip-extras --no-header --annotation-style=line \
    -o requirements.txt requirements.in
  pip-compile --quiet ${UPGRADE} --strip-extras --no-header --annotation-style=line \
    -o requirements-dev.txt requirements-dev.in
"

# Prepend the provenance header pip-compile no longer writes (--no-header keeps
# the diff about versions only).
for lock in requirements.txt requirements-dev.txt; do
  src="${lock%.txt}.in"
  {
    echo "# Generated by scripts/update_requirements.sh from ${src} with Python 3.14."
    echo "# Do not edit: change ${src} and run the script."
    # pip-compile keeps the old header with --upgrade-package (--only): never two headers
    grep -v -e '^# Generated by scripts/update_requirements.sh' -e '^# Do not edit: change' "$lock"
  } > "$lock.tmp" && mv "$lock.tmp" "$lock"
done
echo "==> Locks written: requirements.txt requirements-dev.txt"
